#ifndef DIGITA_HOOKSHOT_TIP_MM_H
#define DIGITA_HOOKSHOT_TIP_MM_H

#include "ultra64.h"
#include "global.h"

extern u64 gDigitaMMHookshotTipDL_metal_gilded_ci8[];
extern u64 gDigitaMMHookshotTipDL_metal_gilded_pal_rgba16[];
extern u64 gDigitaMMHookshotTipDL_metal_gold_ci8[];
extern u64 gDigitaMMHookshotTipDL_metal_gold_pal_rgba16[];
extern Vtx gDigitaMMHookshotTipDL_gDigitaMMHookshotTipDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDigitaMMHookshotTipDL_gDigitaMMHookshotTipDL_mesh_layer_Opaque_vtx_0[14];
extern Gfx gDigitaMMHookshotTipDL_gDigitaMMHookshotTipDL_mesh_layer_Opaque_tri_0[];
extern Vtx gDigitaMMHookshotTipDL_gDigitaMMHookshotTipDL_mesh_layer_Opaque_vtx_1[27];
extern Gfx gDigitaMMHookshotTipDL_gDigitaMMHookshotTipDL_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gDigitaMMHookshotTipDL_metal_gold_layerOpaque[];
extern Gfx mat_revert_gDigitaMMHookshotTipDL_metal_gold_layerOpaque[];
extern Gfx mat_gDigitaMMHookshotTipDL_metal_darkgold_layerOpaque[];
extern Gfx mat_revert_gDigitaMMHookshotTipDL_metal_darkgold_layerOpaque[];
extern Gfx gDigitaMMHookshotTipDL[];

#endif
