#ifndef DIGITA_GILDED_HILT_H
#define DIGITA_GILDED_HILT_H

#include "ultra64.h"
#include "global.h"

extern u64 gDigitaGildedHiltDL_sheath_ci8[];
extern u64 gDigitaGildedHiltDL_sheath_pal_rgba16[];
extern u64 gDigitaGildedHiltDL_metal_gilded_ci8[];
extern u64 gDigitaGildedHiltDL_metal_gilded_pal_rgba16[];
extern u64 gDigitaGildedHiltDL_metal_grey_i8[];
extern u64 gDigitaGildedHiltDL_oot_improved_eq_metal_bombchu_ci8[];
extern u64 gDigitaGildedHiltDL_oot_improved_eq_metal_bombchu_pal_rgba16[];
extern Vtx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_vtx_0[51];
extern Gfx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_tri_0[];
extern Vtx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_vtx_1[12];
extern Gfx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_tri_1[];
extern Vtx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_vtx_2[192];
extern Gfx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_tri_2[];
extern Vtx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_vtx_3[16];
extern Gfx gDigitaGildedHiltDL_gDigitaGildedHiltDL_mesh_layer_Opaque_tri_3[];
extern Gfx mat_gDigitaGildedHiltDL_razor_sheath_layerOpaque[];
extern Gfx mat_revert_gDigitaGildedHiltDL_razor_sheath_layerOpaque[];
extern Gfx mat_gDigitaGildedHiltDL_metal_gold_layerOpaque[];
extern Gfx mat_revert_gDigitaGildedHiltDL_metal_gold_layerOpaque[];
extern Gfx mat_gDigitaGildedHiltDL_metal_layerOpaque[];
extern Gfx mat_revert_gDigitaGildedHiltDL_metal_layerOpaque[];
extern Gfx mat_gDigitaGildedHiltDL_metal_blue_layerOpaque[];
extern Gfx mat_revert_gDigitaGildedHiltDL_metal_blue_layerOpaque[];
extern Gfx gDigitaGildedHiltDL[];

#endif
