#ifndef DIGITA_HOOKSHOT_H
#define DIGITA_HOOKSHOT_H

#include "ultra64.h"
#include "global.h"

extern u64 gDigitaHumanHookshotDL_bow2_ci8[];
extern u64 gDigitaHumanHookshotDL_bow2_pal_rgba16[];
extern u64 gDigitaHumanHookshotDL_bow_ci8[];
extern u64 gDigitaHumanHookshotDL_bow_pal_rgba16[];
extern u64 gDigitaHumanHookshotDL_metal_gilded_ci8[];
extern u64 gDigitaHumanHookshotDL_metal_gilded_pal_rgba16[];
extern u64 gDigitaHumanHookshotDL_MMhookshot_ci8[];
extern u64 gDigitaHumanHookshotDL_MMhookshot_pal_rgba16[];
extern Vtx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_vtx_0[27];
extern Gfx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_tri_0[];
extern Vtx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_vtx_1[23];
extern Gfx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_tri_1[];
extern Vtx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_vtx_2[14];
extern Gfx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_tri_2[];
extern Vtx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_vtx_3[18];
extern Gfx gDigitaHumanHookshotDL_gDigitaHumanHookshotDL_mesh_layer_Opaque_tri_3[];
extern Gfx mat_gDigitaHumanHookshotDL_bow2_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanHookshotDL_bow2_layerOpaque[];
extern Gfx mat_gDigitaHumanHookshotDL_bow_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanHookshotDL_bow_layerOpaque[];
extern Gfx mat_gDigitaHumanHookshotDL_metal_gilded_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanHookshotDL_metal_gilded_layerOpaque[];
extern Gfx mat_gDigitaHumanHookshotDL_hookshot_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanHookshotDL_hookshot_layerOpaque[];
extern Gfx gDigitaHumanHookshotDL[];

#endif
