#ifndef DIGITA_MIRRORSHIELD_H
#define DIGITA_MIRRORSHIELD_H

#include "ultra64.h"
#include "global.h"

extern u64 gDigitaHumanMirrorShieldDL_mirror_face_ia8[];
extern u64 gDigitaHumanMirrorShieldDL_tex_01D340_i8_png_001_i8[];
extern u64 gDigitaHumanMirrorShieldDL_tex_01D440_i8_png_001_i8[];
extern u64 gDigitaHumanMirrorShieldDL_tex_01D300_i8_png_001_i8[];
extern u64 gDigitaHumanMirrorShieldDL_tex_01C800_rgba16_png_001_rgba16[];
extern u64 gDigitaHumanMirrorShieldDL_leather_strap_rgba16[];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Transparent_vtx_cull[8];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Transparent_vtx_0[30];
extern Gfx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Transparent_tri_0[];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_vtx_0[27];
extern Gfx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_tri_0[];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_vtx_1[116];
extern Gfx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_tri_1[];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_vtx_2[20];
extern Gfx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_tri_2[];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_vtx_3[60];
extern Gfx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_tri_3[];
extern Vtx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_vtx_4[17];
extern Gfx gDigitaHumanMirrorShieldDL_gDigitaHumanMirrorShieldDL_mesh_layer_Opaque_tri_4[];
extern Gfx mat_gDigitaHumanMirrorShieldDL_mirror_face_layerTransparent[];
extern Gfx mat_revert_gDigitaHumanMirrorShieldDL_mirror_face_layerTransparent[];
extern Gfx mat_gDigitaHumanMirrorShieldDL_mirror_surface_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanMirrorShieldDL_mirror_surface_layerOpaque[];
extern Gfx mat_gDigitaHumanMirrorShieldDL_mirror_front_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanMirrorShieldDL_mirror_front_layerOpaque[];
extern Gfx mat_gDigitaHumanMirrorShieldDL_mirror_back_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanMirrorShieldDL_mirror_back_layerOpaque[];
extern Gfx mat_gDigitaHumanMirrorShieldDL_mirror_side_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanMirrorShieldDL_mirror_side_layerOpaque[];
extern Gfx mat_gDigitaHumanMirrorShieldDL_belt_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanMirrorShieldDL_belt_layerOpaque[];
extern Gfx gDigitaHumanMirrorShieldTransparentDL[];
extern Gfx gDigitaHumanMirrorShieldOpaqueDL[];
extern Gfx gDigitaHumanMirrorShieldDL[];

#endif
