#ifndef DIGITA_MASTER_SHEATH_H
#define DIGITA_MASTER_SHEATH_H

#include "ultra64.h"
#include "global.h"

extern u64 gDigitaMasterSheathDL_SheathTex_rgba16[];
extern Vtx gDigitaMasterSheathDL_gDigitaMasterSheathDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDigitaMasterSheathDL_gDigitaMasterSheathDL_mesh_layer_Opaque_vtx_0[54];
extern Gfx gDigitaMasterSheathDL_gDigitaMasterSheathDL_mesh_layer_Opaque_tri_0[];
extern Vtx gDigitaMasterSheathDL_gDigitaMasterSheathDL_mesh_layer_Opaque_vtx_1[8];
extern Gfx gDigitaMasterSheathDL_gDigitaMasterSheathDL_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gDigitaMasterSheathDL_sheath_master_layerOpaque[];
extern Gfx mat_revert_gDigitaMasterSheathDL_sheath_master_layerOpaque[];
extern Gfx mat_gDigitaMasterSheathDL_sheath_hole_layerOpaque[];
extern Gfx mat_revert_gDigitaMasterSheathDL_sheath_hole_layerOpaque[];
extern Gfx gDigitaMasterSheathDL[];

#endif
