#ifndef DIGITA_GILDEDBLADE_H
#define DIGITA_GILDEDBLADE_H

#include "ultra64.h"
#include "global.h"

extern u64 gDigitaHumanGildedBladeDL_metal_termina_rgba16[];
extern u64 gDigitaHumanGildedBladeDL_metal_grey_i8[];
extern Vtx gDigitaHumanGildedBladeDL_gDigitaHumanGildedBladeDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gDigitaHumanGildedBladeDL_gDigitaHumanGildedBladeDL_mesh_layer_Opaque_vtx_0[84];
extern Gfx gDigitaHumanGildedBladeDL_gDigitaHumanGildedBladeDL_mesh_layer_Opaque_tri_0[];
extern Vtx gDigitaHumanGildedBladeDL_gDigitaHumanGildedBladeDL_mesh_layer_Opaque_vtx_1[39];
extern Gfx gDigitaHumanGildedBladeDL_gDigitaHumanGildedBladeDL_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gDigitaHumanGildedBladeDL_metal_termina_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanGildedBladeDL_metal_termina_layerOpaque[];
extern Gfx mat_gDigitaHumanGildedBladeDL_metal_001_layerOpaque[];
extern Gfx mat_revert_gDigitaHumanGildedBladeDL_metal_001_layerOpaque[];
extern Gfx gDigitaHumanGildedBladeDL[];

#endif
